---

- name: merge pipewire packages between defaults and custom
  ansible.builtin.set_fact:
    pipewire_packages: "{{ pipewire_packages | union(pipewire_defaults_packages) | sort | unique }}"

- name: install package
  ansible.builtin.package:
    name: "{{ pipewire_packages }}"
    state: present

# - name: get information
#   ansible.builtin.command: |
#     ansible --version
#   register: pipewire_information
#
# - name: define ansible version
#   ansible.builtin.set_fact:
#     pipewire_version: "{{ pipewire_information.version }}"
#     pipewire_major_version: "{{ pipewire_information.major_version }}"
#   when:
#     - pipewire_information.rc == 0
#
# - name: create custom fact file
#   bodsch.core.facts:
#     name: ansible
#     facts:
#       version: "{{ pipewire_version }}"
#       major_version: "{{ pipewire_major_version }}"

...
