---

pipewire_enable_pulse: true
pipewire_enable_alsa: true
pipewire_enable_bluetooth: true

pipewire_global_config:
  clock_rate: 48000
  clock_allowed_rates:
    - 44100
    - 48000
  quantum: 512
  min_quantum: 32
  max_quantum: 1024

pipewire_pulse_properties:
  pulse.min.req: "256/48000"

pipewire_client_properties:
  resample.quality: 4

# applied on wireplumber >= 0.5 (spa-json)
pipewire_wireplumber_settings:
  device.routes.default-sink-volume: 0.6

# applied on wireplumber 0.4 (lua)
pipewire_wireplumber_lua:
  - 'alsa_monitor.properties["alsa.midi"] = false'

pipewire_users:
  - name: bob

  - name: pipetester
    config:
      global:
        clock_rate: 44100
      pulse_properties:
        pulse.default.req: "1024/48000"

...
