---

# --- per user configuration ---------------------------------------------------------

- name: configure per user
  when:
    - not running_in_check_mode
    - pipewire_normalized_users | default([]) | count > 0
  ansible.builtin.include_tasks: user.yml
  loop: "{{ pipewire_normalized_users | default([]) }}"
  loop_control:
    loop_var: pipewire_user
    label: "{{ pipewire_user.name }}"

...
